### PR TITLE
implementing colspan

### PR DESCRIPTION
**Pull request by domm**
Hi!

This is a first implementation for the colspan feature requested in issue #46.

The code works (at least for some semi-complicated data), `see examples/issue46_colspan.pl`. Tests and docs are still missing, but I will add them if you agree with the general direction of the implementation.

Looking forward for some feedback,
Greeting,
domm

### CODE REVIEW

**Comment by abeverley** [comment]
@kamenov - would it be possible to get your comments on this PR please? No need for a merge at this stage, it would just be good to know if you are happy with the general direction. Many thanks.

**Comment by kamenov** [comment]
Sorry for the delay. Looks good. Go ahead.

**Comment by abeverley** [comment]
Thanks @kamenov

**Comment by domm** [comment]
I now added docs and a test (t/Colspan.t). I've also updated/moved the example script to examples/colspan.pl

From my point of view I'm done.

@kamenov but if you have any suggestions for adaptions, please tell me!

Greetings,
domm

**Comment by abeverley** [comment]
@kamenov - have you had a chance to look at this PR at all yet please? Many thanks.

**Comment by kamenov** [comment]
Tagged as 0.11.0 and uploaded to CPAN. I've missed the prev. reminder.

**Comment by abeverley** [comment]
Brilliant, thanks @kamenov

**Comment by kamenov** [comment]
0.11.0  has been indexed and there are many PASS reports from CPAN Testers.

Thank you for your contributions!

**Pull request merged**
